
package com.bootcampjava.electricityservice.soapservice;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "PowerPlanService", targetNamespace = "http://serviceplan.soapservice.webservices.services.electricityservice.cmsenergy.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface PowerPlanService {


    /**
     * 
     * @return
     *     returns java.util.List<com.bootcampjava.electricityservice.soapservice.Service>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getServicePlans", targetNamespace = "http://serviceplan.soapservice.webservices.services.electricityservice.cmsenergy.com/", className = "com.bootcampjava.electricityservice.soapservice.GetServicePlans")
    @ResponseWrapper(localName = "getServicePlansResponse", targetNamespace = "http://serviceplan.soapservice.webservices.services.electricityservice.cmsenergy.com/", className = "com.bootcampjava.electricityservice.soapservice.GetServicePlansResponse")
    public List<Service> getServicePlans();

}
